structure(list(url = "https://app.crunch.io/api/", status_code = 401L, 
    headers = structure(list(date = "Fri, 22 May 2020 22:57:41 GMT", 
        `content-type` = "application/json", `content-length` = "168", 
        server = "nginx", `content-encoding` = "gzip", vary = "Accept-Encoding", 
        allow = "GET, HEAD, OPTIONS, POST"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/2", 
        headers = structure(list(date = "Fri, 22 May 2020 22:57:41 GMT", 
            `content-type` = "application/json", `content-length` = "168", 
            server = "nginx", `content-encoding` = "gzip", vary = "Accept-Encoding", 
            allow = "GET, HEAD, OPTIONS, POST"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"status\": \"401 Unauthorized\", \"urls\": {\"login_url\": \"https://app.crunch.io/api/public/login/\", \"password_reset_url\": \"https://app.crunch.io/api/public/password_reset/\", \"public_url\": \"https://app.crunch.io/api/public/\", \"email_change_url\": \"https://app.crunch.io/api/public/change_email/\", \"password_change_url\": \"https://app.crunch.io/api/public/password_change/\", \"collect_inquires\": \"https://app.crunch.io/api/public/inquire/\"}}"), 
    date = structure(1590188261, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.7e-05, pretransfer = 7.4e-05, starttransfer = 0.312317, 
    total = 0.312469)), class = "response")
