structure(list(url = "https://app.crunch.io/api/sources/", status_code = 201L, 
    headers = structure(list(date = "Fri, 17 Jul 2020 19:21:54 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "86", 
        location = "https://app.crunch.io/api/sources/7b9dc2/", 
        server = "nginx", `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
        allow = "GET, HEAD, OPTIONS, POST", `x-timing` = ""), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
        headers = structure(list(date = "Fri, 17 Jul 2020 19:21:54 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `content-length` = "86", location = "https://app.crunch.io/api/sources/7b9dc2/", 
            server = "nginx", `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
            allow = "GET, HEAD, OPTIONS, POST", `x-timing` = ""), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"element\": \"shoji:view\", \"self\": \"https://app.crunch.io/api/sources/\"}"), 
    date = structure(1595013714, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.4e-05, 
    connect = 3.5e-05, pretransfer = 0.000149, starttransfer = 0.000154, 
    total = 0.529916)), class = "response")
