structure(list(url = "https://app.crunch.io/api/sources/", status_code = 201L, 
    headers = structure(list(date = "Sat, 06 Jun 2020 19:28:02 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "86", 
        location = "https://app.crunch.io/api/sources/5ad553/", 
        server = "nginx", `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
        allow = "GET, HEAD, OPTIONS, POST", `x-timing` = "", 
        `set-cookie` = "REDACTED"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
        headers = structure(list(date = "Sat, 06 Jun 2020 19:28:02 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `content-length` = "86", location = "https://app.crunch.io/api/sources/5ad553/", 
            server = "nginx", `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
            allow = "GET, HEAD, OPTIONS, POST", `x-timing` = "", 
            `set-cookie` = "REDACTED"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".crunch.io", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1623007682, class = c("POSIXct", 
        "POSIXt")), name = "token", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"element\": \"shoji:view\", \"self\": \"https://app.crunch.io/api/sources/\"}"), 
    date = structure(1591471682, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.2e-05, 
    connect = 7.3e-05, pretransfer = 0.000181, starttransfer = 0.000182, 
    total = 0.546187)), class = "response")
