name: CI

"on":
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container: 1beb/ygbds

    steps:
    - uses: actions/checkout@v2
    - name: Install tinytex
      run: | 
        Rscript -e "install.packages(c('tinytex', 'httptest'))"
        Rscript -e "tinytex::install_tinytex()"
    - name: Build
      run: R CMD build --no-build-vignettes --no-manual .
    - name: Check
      run: |
        R CMD check --no-vignettes --no-manual crunchtabs_*.tar.gz
    - name: Dispatch for Internal Integration Tests
      run: |
       curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/yougov-datacience/crunchtabs_internal_tests/dispatches --data '{"event_type": "run_integration_tests"}'
