name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 1beb/crunchtabs

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: R CMD build --no-build-vignettes --no-manual .
    - name: Check
      run: |
        R CMD check --no-vignettes --ignore-vignettes --no-manual crunchtabs_*.tar.gz
    - name: Coverage
      run: |
        Rscript -e 'covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")'

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RCheckLog
        path: ‘/__w/crunchtabs/crunchtabs/crunchtabs.Rcheck/00check.log’
