name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 1beb/crunchtabs

    steps:
    - uses: actions/checkout@v2
    - name: Add kableExtra
      run: Rscript -e 'install.packages("kableExtra")'
    - name: CRAN crunch
      run: Rscript -e 'install.packages("crunch")'
    - name: Build
      run: R CMD build --no-build-vignettes --no-manual .
    - name: Check
      run: |
        R CMD check --no-vignettes --ignore-vignettes --no-manual crunchtabs_*.tar.gz
    - name: Coverage
      run: |
        Rscript -e 'covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")'
