name: PackageDown

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 1beb/crunchtabs

    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: | 
        git config --global user.email "Marvin the Paranoid Android"
        git config --global user.name "marvin@heart-of-gold.co.uk"
    - name: Deploy package
      run: pkgdown::deploy_to_branch(new_process = FALSE, lazy = FALSE)
      shell: Rscript {0}
