name: PackageDown

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    container: 1beb/crunchtabs

    steps:
    - uses: actions/checkout@v2
    - name: Deploy package
      run: pkgdown::deploy_to_branch(new_process = FALSE)
      shell: Rscript {0}
